name: Docker

on:
  push:
    branches: [ "main" ]
    tags:
      - '*'
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      actions: write
      checks: write
      contents: write
      deployments: write
      id-token: write
      issues: write
      pull-requests: write
      security-events: write
      statuses: write

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ github.repository }}
        tags: |
          type=raw,value=latest,enable={{is_default_branch}}
          type=raw,value=pr-{{github.event.pull_request.number}},enable={{is_pr}}
          type=semver,pattern={{version}}
          type=semver,pattern={{major}}.{{minor}}
          type=semver,pattern={{major}}

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      if: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.base_ref == 'main' && !github.event.pull_request.head.repo.fork) }}
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64,linux/arm64,linux/arm
        build-args: |
          VERSION=${{ github.ref_name }}
          SHA=${{ github.sha }}
        push: ${{ github.event_name != 'pull_request' || (github.event_name == 'pull_request' && github.base_ref == 'main' && !github.event.pull_request.head.repo.fork) }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
